plugins/easy_instant_messages/config/routes.rb
if Redmine::Plugin.installed?(:easy_instant_messages)
  resources :easy_instant_messages do
    collection do
      get :contacts
      get :freetext_users
      put :toggle_sound
      put :toggle_hidden_user_id
      get :chat, to: 'easy_instant_messages#show_easy_chat'

      get :conversations
      get :contacts
      put :read
      # delete :destroy_all
    end
    member do
      get :reply_to
      get :history
      get :conversation
    end
  end
end

plugins/easy_instant_messages/app/models/easy_instant_conversation.rb
class EasyInstantConversation < Struct.new(:secondparty, :messages)
  class << self
    def for_user(user)
      messages = ActiveSupport::OrderedHash.new {|hsh, key| hsh[key] = []}; batch_size = 25
      ids = EasyInstantMessage.all_for_user(user).order(created_at: :desc).ids
      ids.each_slice(batch_size) do |chunk|
        EasyInstantMessage.where(id: chunk).order(created_at: :desc).preload(:recipient).each do |im|
          messages[im.sender_id] << im
          break if messages.keys.size == 10
        end
        break if messages.keys.size == 10 || messages.values.size == (batch_size * 2)
      end

      User.where(id: (messages.keys - [user.id])).preload(:email_address).collect do |user|
        EasyInstantConversation.new(user, messages[user.id].sort_by(&:created_at))
      end.sort { |a, b| b.last_message <=> a.last_message }
    end

    def between_users(firstparty, secondparty)
      firstparty_id = firstparty.id
      secondparty_id = secondparty.id

      # messages = EasyInstantMessage.where("(sender_id = ? AND recipient_id =?) OR (recipient_id = ? AND sender_id = ?)", firstparty_id, secondparty_id, firstparty_id, secondparty_id).order('created_at ASC').preload(:sender).last(15)
      messages = EasyInstantMessage.where("(sender_id = ? AND recipient_id =?) OR (recipient_id = ? AND sender_id = ?)", firstparty_id, secondparty_id, firstparty_id, secondparty_id).order('created_at ASC').preload(:sender)

      new(secondparty, messages)
    end

    private

    # sorts conversations by their last message's creation time
    def sort_groups(groups)
      groups.sort_by { |_, messages| messages.last.created_at }.reverse
    end
  end

  def last_message
    @last_message ||= messages.last
  end

  def unread_messages
    messages.select { |m| m.sender_id == secondparty.id && m.unread }
  end

  def num_of_unread_messages
    unread_messages.size
  end

  def mark_read
    EasyInstantMessage.where(id: unread_messages.map(&:id)).update_all(unread: false)
  end

  def to_partial_path
    'conversation'
  end
end

plugins/easy_instant_messages/app/models/easy_instant_message.rb
class EasyInstantMessage < ActiveRecord::Base
  include Redmine::SafeAttributes

  belongs_to :sender, class_name: 'User'
  belongs_to :recipient, class_name: 'User'

  validates :content, :recipient_id, presence: true
  validate :cant_send_message_to_self

  scope :for_user, lambda { |user = User.current| where(recipient_id: user) }
  scope :all_for_user, lambda { |user = User.current| joins(:sender, :recipient).where(users: {status: User::STATUS_ACTIVE}, recipients_easy_instant_messages: {status: User::STATUS_ACTIVE}).where("#{EasyInstantMessage.table_name}.sender_id = :u OR #{EasyInstantMessage.table_name}.recipient_id = :u", {u: user.id}) }

  safe_attributes 'recipient_id', 'content'

  if Redmine::Plugin.installed?(:easy_extensions)
    html_fragment :content, scrub: :strip
  end

  before_create :strip_content

  def self.is_muted?
    Rails.cache.fetch [:easy_instant_message, :mute_messaging, User.current] do
      !User.current.pref.others[:easy_instant_message_mute].nil?
    end
  end

  def strip_content
    self.content.strip!
  end

  def cant_send_message_to_self
    errors[:base] << l(:error_easy_instant_messages_send_message_to_self) if sender_id == recipient_id
  end

  def notified_users
    [recipient]
  end

end

plugins/easy_instant_messages/app/controllers/easy_instant_messages_controller.rb
class EasyInstantMessagesController < ApplicationController
  accept_api_auth :index, :read, :show_easy_chat

  before_action :require_login

  def index
    @easy_instant_messages = EasyInstantMessage.for_user(User.current).where(:unread => true).order(:created_at)
    respond_to do |format|
      format.js {@easy_instant_messages = @easy_instant_messages.all}
      # format.xml {render :xml => @easy_instant_messages}
      # format.json {render :json => @easy_instant_messages}
      format.api
    end
  end

  def conversations
    @conversations = EasyInstantConversation.for_user(User.current)

    respond_to do |format|
      format.js
    end
  end

  def conversation
    @conversation = EasyInstantConversation.between_users(User.current, User.find(params[:id]))
    @num_of_unread_messages_before_read = @conversation.num_of_unread_messages
    @conversation.mark_read

    respond_to do |format|
      format.html
      format.js {
        @conversation.messages = @conversation.messages.last(15)
      }
    end
  end

  def show_easy_chat
    # scope = EasyInstantMessage.for_user(User.current).order(created_at: :desc)
    # if (@easy_instant_messages = scope.preload(sender: [:email_address]).where(unread: true).to_a).present?
    #   if @easy_instant_messages.map(&:sender_id).uniq.count == 1
    #     @user = @easy_instant_messages.first.sender
    #     # scope.where(unread: true).update_all(unread: false)
    #
    #     respond_to do |format|
    #       format.js do
    #         @open_new_chat = true
    #         return new
    #       end
    #     end
    #   end
    # else
    #   # TODO: Get top 5 senders
    #   easy_instant_messages = {}
    #   scope.select(:sender_id, :created_at).first(100).each do |msg|
    #     easy_instant_messages[msg.sender_id] ||= scope.where(sender_id: msg.sender_id).limit(1).pluck(:id)
    #     break if easy_instant_messages.keys.count == 5
    #   end
    #   @easy_instant_messages = EasyInstantMessage.for_user(User.current).where(id: easy_instant_messages.values.flatten).preload(sender: [:email_address]).order(created_at: :desc).to_a
    # end

    @conversations = EasyInstantConversation.for_user(User.current)

    respond_to do |format|
      format.js
    end
  end

  def contacts
    @contacts = User.active.like(params[:q]).where.not(id: User.current.id) # do not include current user himself
    @contacts = @contacts.easy_type_internal if defined?(EasyExtensions)

    respond_to do |format|
      format.js
    end
  end

  def create
    @easy_instant_message = EasyInstantMessage.new(:sender => User.current)
    @easy_instant_message.safe_attributes = params[:easy_instant_message]
    @easy_instant_message.sender_ip = request.remote_ip

    respond_to do |format|
      if @easy_instant_message.save
        format.js {@exit = {:type => 'notice', :text => l(:notice_easy_instant_message_sended)}}
      else
        format.js {@exit = {:type => 'error', :text => ''}}
      end
    end
  end

  def read
    @easy_instant_message = EasyInstantMessage.find(params[:id])

    if @easy_instant_message.update_attributes(unread: false)
      head :ok
    end
  end

  def toggle_sound
    @user = User.current
    Rails.cache.delete [:easy_instant_message, :mute_messaging, @user]
    if @user.pref.others[:easy_instant_message_mute]
      @user.pref.others.delete(:easy_instant_message_mute)
    else
      @user.pref.others[:easy_instant_message_mute] = true
    end
    @user.pref.save
    respond_to do |format|
      format.js
    end
  end
end

plugins/easy_instant_messages/app/helpers/easy_instant_messages_helper.rb
module EasyInstantMessagesHelper
  include EasyAttendancesHelper if defined?(EasyAttendancesHelper)

  def easy_instant_messages_avatar_url(user = nil)
    if defined? avatar_url
      avatar_url(user)
    else
      user ||= User.current
      result = if Setting.gravatar_enabled?
                 options = {:ssl => (request && request.ssl?), :default => Setting.gravatar_default}
                 email = nil
                 if user.respond_to?(:mail)
                   email = user.mail
                 elsif user.to_s =~ %r{<(.+?)>}
                   email = $1
                 end
                 gravatar_url(email, options)
               elsif user.respond_to?(:easy_avatar) && (av = user.easy_avatar).present? && (img_url = av.image.url(:small))
                 get_easy_absolute_uri_for(img_url).to_s
               end
      result
    end
  end

  def easy_logo
    image_tag 'easy-logo.svg', plugin: :easy_instant_messages
  end

  def back_arrow
    image_tag 'back-arrow.svg', plugin: :easy_instant_messages
  end
end

plugins/easy_instant_messages/app/views/easy_instant_messages/_contact.html.erb
<div class="easyim__contact <%= 'easyim__contact--dark' if local_assigns.fetch(:dark, false) %>">
  <% if local_assigns.fetch(:show_link, false) %>
    <%= link_to "", conversation_easy_instant_message_path(contact.id), class: "easyim__overlay-link", remote: true %>
  <% end %>

  <div class="easyim__avatar"><%= avatar(contact, style: :medium) %></div>
  <h3 class="easyim__contact__name"><%= link_to_user(contact) %></h3>

  <%= link_to conversation_easy_instant_message_path(contact.id), class: 'easyim__contact__history' do %>
    <%= image_tag('history.svg', plugin: :easy_instant_messages) %>
  <% end %>
</div>

plugins/easy_instant_messages/app/views/easy_instant_messages/_easy_instant_messages_tooltip_container.html.erb
<div id="easy_instant_messages_container" class="easyim__container">
  <div id="easy_instant_messages_header" class="easyim__header">
    <%= render partial: 'easy_instant_messages/headers/conversations' %>
  </div>

  <div id="easy_instant_messages_body" class="easyim__body">
    <%= render partial: 'easy_instant_messages/conversations/conversation_overview', collection: @conversations, as: :conversation %>
  </div>
</div>

plugins/easy_instant_messages/app/views/easy_instant_messages/_overview.html.erb
<div class="easyim__overview <%= 'easyim__overview--highlight' if overview.num_of_unread_messages.positive? %>">
  <%= link_to "", conversation_easy_instant_message_path(overview.sender.id), class: "easyim__overview__overlay-link", remote: true %>

  <div class="easyim__overview__pre">
    <div class="easyim__avatar"><%= avatar(overview.sender) %></div>
  </div>

  <div class="easyim__overview__content">
    <div class="easyim__overview__title-wrapper">
      <h4 class="easyim__overview__title"><%= overview.sender.name %></h4>

      <span class="easyim__overview__timestamp">
        <%= distance_of_time_in_words(Time.now, overview.last_message.created_at) %>
      </span>
    </div>

    <div class="easyim__overview__subtitle-wrapper">
      <p class="easyim__overview__subtitle"><%= overview.last_message.content %></p>

      <% if overview.num_of_unread_messages.positive? %>
          <span class="easyim__overview__unread-count"><%= overview.num_of_unread_messages %></span>
      <% end %>
    </div>
  </div>
</div>

plugins/easy_instant_messages/app/views/easy_instant_messages/_render_easy_instant_messages_box.html.erb
<% if User.current.allowed_to_globally?(:use_easy_instant_messages, {}) %>
  <% if Redmine::Plugin.installed?(:easy_extensions) %>
    <%= stylesheet_link_tag('easy_instant_messages_easy') %>
    <%= javascript_include_tag('easy_instant_messages', defer: true) %>
  <% else %>
    <%= stylesheet_link_tag('easy_instant_messages_raw', plugin: 'easy_instant_messages') %>
    <%= javascript_include_tag('easy_instant_messages', plugin: 'easy_instant_messages', defer: true) %>
  <% end %>

  <script type="text/javascript">
    EASY.schedule.require(function () {
      window.EasyInstantMessenger = new EasyInstantMessaging({
        checkMessageUrl: '<%= easy_instant_messages_path(format: 'json') %>',
        newChatUrl: '<%= new_easy_instant_message_path %>',
        readMessageUrl: '<%= read_easy_instant_messages_path(format: 'json') %>',
        apiKey: '<%= User.current.api_key %>',
        soundEnabled: <%= !EasyInstantMessage.is_muted?  %>
      });
      $(document).trigger('easy_IM_loaded');
    }, function () {
      return window.EasyInstantMessaging;
    });
  </script>

  <% unless EasyInstantMessage.is_muted? %>
    <%= render 'easy_instant_messages/audio_tag' %>
  <% end %>

  <% unless Redmine::Plugin.installed?(:easy_extensions) %>
    <%= link_to '', conversations_easy_instant_messages_path, id: "easy_instant_messages_toggle", class: "easyim__redmine-toggle", remote: true %>
  <% end %>

  <div id="easy_instant_messages_wrapper" class="easyim__wrapper easyim__wrapper--hidden">
    <div id="easy_instant_messages_container" class="easyim__container">
      <span id="easy_instant_messages_top_close" class="easyim__top-close"><%= image_tag 'close.svg', plugin: :easy_instant_messages %></span>
      <div id="easy_instant_messages_header" class="easyim__header"></div>
      <div id="easy_instant_messages_body" class="easyim__body"></div>
    </div>
  </div>
<% end %>

plugins/easy_instant_messages/app/views/easy_instant_messages/_search_contacts.html.erb
<%= form_tag contacts_easy_instant_messages_path, method: :get, class: 'easyim__search-form', remote: true do %>
  <%= text_field_tag :q, nil, placeholder: t(:placeholder_easy_instant_messages_search_users), class: 'easyim__search-input', autocomplete: 'off' %>
  <%= button_tag 'S', type: :submit, class: 'easyim__search-btn' do %>
    <%= image_tag('search.svg', plugin: :easy_instant_messages) %>
  <% end %>
<% end %>

plugins/easy_instant_messages/app/views/easy_instant_messages/contacts.js.erb
$("#easy_instant_messages_body").html("<%= j render partial: 'contact', collection: @contacts, locals: { dark: true, show_link: true } %>");

EasyInstantMessenger.setDefaultInterval();

<% if Redmine::Plugin.installed?(:easy_attendances) %>
  LazyLoader.refresh();
<% end %>

plugins/easy_instant_messages/app/views/easy_instant_messages/conversation.html.erb
<!--Renders action -->
<!--Partial: '_conversation' - common for JS -->

<%= render partial: 'easy_instant_messages/contact', locals: { contact: @conversation.secondparty, dark: true, omit_link: true } %>
<%= render @conversation %>

plugins/easy_instant_messages/app/views/easy_instant_messages/conversation.js.erb
$("#easy_instant_messages_header").html("<%= j render partial: 'easy_instant_messages/headers/conversation', locals: { conversation: @conversation } %>");
$("#easy_instant_messages_body").html("<%= j render @conversation %>").append("<%= j render partial: 'easy_instant_messages/conversation/submit_form', locals: { conversation: @conversation } %>");

EasyInstantMessenger.scrollToBottomOfChatWindow();
if (!window.ERUI || !ERUI.isMobile) EasyInstantMessenger.focusSubmitInput();
EasyInstantMessenger.watchSubmitInput();

EasyInstantMessenger.setHyperInterval();

EasyInstantMessenger.newMessagesCount -= parseInt("<%= @num_of_unread_messages_before_read %>");
EasyInstantMessenger.displayReceivedMessagesCount();

<% if Redmine::Plugin.installed?(:easy_attendances) %>
  LazyLoader.refresh();
<% end %>

plugins/easy_instant_messages/app/views/easy_instant_messages/conversation/_message.html.erb
<div class="easyim__message <%= 'mine' if message.sender_id == User.current.id %>" id="easy_instant_messages_message_<%= message.id %>">
  <div class="easyim__message__avatar easyim__avatar <%= 'easyim__message__avatar--hidden' unless local_assigns.fetch(:show_avatar, true) %>">
    <%= avatar(message.sender, style: :medium) %>
  </div>

  <div class="easyim__message__content-wrapper">
    <div class="easyim__message__timestamp <%= 'easyim__message__timestamp--right' if message.sender_id == User.current.id %>">
      <%= format_time(message.created_at) %>
    </div>
    <div class="easyim__message__content <%= 'easyim__message__content--grey' if message.sender_id == User.current.id %>" title="<%= format_time(message.created_at) %>">
      <%= textilizable(message.content) %>
    </div>
  </div>
</div>

plugins/easy_instant_messages/app/views/easy_instant_messages/conversation/_submit_form.html.erb
<%= labelled_form_for(EasyInstantMessage.new(recipient_id: conversation.secondparty.id), remote: true, html: { class: "easyim__submit-form easyim__conversation__submit-form" }) do |f| %>
  <%= f.hidden_field(:recipient_id) %>
  <%= f.text_area(:content, class: "easyim__submit-form__textarea autoExpand", no_label: true, placeholder: t(:placeholder_easy_instant_messages_prompt_to_type), rows: 1, autocomplete: "off") %>

  <%= f.button type: :submit, class: "easyim__submit-form__submit-btn" do %>
      <%= image_tag('submit-arrow.svg', plugin: :easy_instant_messages) %>
  <% end %>
<% end %>

plugins/easy_instant_messages/app/views/easy_instant_messages/conversations.js.erb
$("#easy_instant_messages_header").html("<%= j render partial: 'easy_instant_messages/headers/conversations' %>");
$("#easy_instant_messages_body").html("<%= j render partial: 'easy_instant_messages/conversations/conversation_overview', collection: @conversations, as: :conversation %>");

EasyInstantMessenger.setDefaultInterval();

<% if Redmine::Plugin.installed?(:easy_attendances) %>
  LazyLoader.refresh();
<% end %>

plugins/easy_instant_messages/app/views/easy_instant_messages/conversations/_conversation_overview.html.erb
<div class="easyim__overview easyim__item">
  <%= link_to "", conversation_easy_instant_message_path(conversation.secondparty.id), class: "easyim__overlay-link", remote: true %>

  <div class="easyim__overview__pre easyim__item__pre">
    <div class="easyim__avatar"><%= avatar(conversation.secondparty, style: :medium) %></div>
  </div>

  <div class="easyim__overview__content easyim__item__content">
    <div class="easyim__overview__title-wrapper">
      <h4 class="easyim__overview__title"><%= link_to_user(conversation.secondparty) %></h4>

      <span class="easyim__overview__timestamp">
        <%= distance_of_time_in_words(Time.now, conversation.last_message.created_at) %>
      </span>
    </div>

    <div class="easyim__overview__subtitle">
      <% if conversation.num_of_unread_messages > 0 %>
        <span class="easyim__overview__unread-count"><%= conversation.num_of_unread_messages %></span>
      <% end %>

      <div class="easyim__overview__last-message">
        <% if conversation.last_message.sender_id == User.current.id %>
          <%= l('label_easy_instant_message_you') + ': ' %>
        <% end %>

        <%= strip_tags(textilizable(conversation.last_message.content)) %>
      </div>
    </div>
  </div>
</div>

plugins/easy_instant_messages/app/views/easy_instant_messages/create.js.erb
<% if @easy_instant_message.persisted? %>
  var lastMessage = $("#easy_instant_messages_conversation_messages").find('.easyim__message').last()
  if (lastMessage.hasClass('mine')) {
    lastMessage.find('.easyim__message__avatar').addClass('easyim__avatar easyim__message__avatar--hidden')
  }

  $("#easy_instant_message_content").attr('rows',1).val('').focus();
  $("#easy_instant_messages_conversation_messages").append("<%= j render partial: 'easy_instant_messages/conversation/message', locals: { message: @easy_instant_message, show_avatar: true } %>");
  EasyInstantMessenger.scrollToBottomOfChatWindow();
<% end %>

plugins/easy_instant_messages/app/views/easy_instant_messages/headers/_conversation.html.erb
<div class="easyim__item easyim__item--padded">
  <div class="easyim__item__pre easyim__item__pre--smaller">
    <%= link_to back_arrow, conversations_easy_instant_messages_path, class: 'easyim__back-btn', remote: true %>
  </div>

  <div class="easyim__item__content">
    <%= render partial: 'contact', locals: { contact: conversation.secondparty } %>
  </div>
</div>

plugins/easy_instant_messages/app/views/easy_instant_messages/headers/_conversations.html.erb
<div class="easyim__item easyim__item--padded">
  <div class="easyim__item__pre">
    <%= link_to easy_logo, conversations_easy_instant_messages_path, class: "easyim__avatar", remote: true %>
  </div>

  <div class="easyim__item__content">
    <%= render partial: 'easy_instant_messages/search_contacts' %>
  </div>
</div>

plugins/easy_instant_messages/app/views/easy_instant_messages/index.js.erb
//$(function () {
//  var message_trigger = $("a#easy_instant_messages_list_trigger");
//  if (window.easyInstantMessagesTitleNotifier) {
//    window.clearInterval(window.easyInstantMessagesTitleNotifier);
//    easyInsatntMessagesTitleNotifyToggler(true);
//  }
  <!--<%# if @easy_instant_messages.any? %>-->
    <!--<%# easy_instant_message = @easy_instant_messages.first if @easy_instant_messages.one? %>-->
//    message_trigger.addClass('change-color-event');
//    window.easyInstantMessagesTitleNotifier = setInterval(easyInsatntMessagesTitleNotifyToggler, 1500);
//
    <!--<%# unless EasyInstantMessage.is_muted? %>-->
//      if ($("#easy_im_audio_notify_container").html() == "") {
//        var audio = $("<audio/>").attr({autoplay: true});
//        audio.append($("<source/>").attr({src:"<%#=j File.join(Redmine::Plugin.find(:easy_instant_messages).public_directory.gsub(File.join(Rails.root,'public').to_s, ""), 'chat1.ogg') %>", "type":"audio/ogg"}));
//        audio.append($("<source/>").attr({src:"<%#=j File.join(Redmine::Plugin.find(:easy_instant_messages).public_directory.gsub(File.join(Rails.root,'public').to_s, ""), 'chat1.mp3') %>", "type":"audio/mp3"}));
//        audio.append($("<source/>").attr({src:"<%#=j File.join(Redmine::Plugin.find(:easy_instant_messages).public_directory.gsub(File.join(Rails.root,'public').to_s, ""), 'chat1.m4a') %>", "type":"audio/mp4"}));
//        $("#easy_im_audio_notify_container").html(audio);
//      } else {
//        $("#easy_im_audio_notify_container").html("")
//      }
    <!--<%# end %>-->

//    if ($("#easy_instant_message_inline_chat_inputs").is(":visible")) {
      <!--<%# @easy_instant_messages.group_by(&:sender_id).each do |sender_id, messages| %>-->
//        if ($("#easy_instant_message_recipient_id").val() === '<%#= sender_id %>') {
          <!--<%# messages.reverse.each do |message| %>-->
//            if (!$("#inline_history_<%#= dom_id(message) -%>")[0]) {
//              $("#easy_im_inline_message_history").append("<%#=j render(:partial => 'inline_chat_history_item', :locals => {:im => message}) %>");
//            }
          <!--<%# end %>-->
//          $('#easy_im_inline_message_history').scrollTop($('#easy_im_inline_message_history')[0].scrollHeight);
//          if (typeof(document.hidden) !== 'undefined' && !document.hidden) {
//            $.post('<%#= read_easy_instant_messages_path %>', {ids: <%#=j messages.map(&:id).to_s %>});
//          }
//        }
      <!--<%# end -%>-->
//    } else {
      <!--<%# message_ids = @easy_instant_messages.map(&:id) %>-->
//      if ("Notification" in window) {
//        if (Notification.permission === "granted" || (window.webkitNotifications && window.webkitNotifications.checkPermission() === 0)) {
          <!--<%# if easy_instant_message %>-->
//            var notification = new Notification("<%#=j easy_instant_message.sender.name %>",{
//              body: "<%#=j Sanitize.clean(easy_instant_message.content.strip) %>",
//              lang: "<%#= current_language %>",
//              tag: "easy_instant_message"
//            })
//            notification.onclick = function() {
//              window.focus();
//              notification.close();
//              $.get("<%#= show_easy_im_window_easy_instant_messages_path(:ids => message_ids) %>");
//            }
          <!--<%# else %>-->
//            var notification = new Notification("<%#=j l(:title_easy_instant_messages_notifier) %>",{
//              body: "<%#=j l(:text_easy_instant_messages_notifier, :count => @easy_instant_messages.count) %>",
//              lang: "<%#= current_language %>",
//              tag: "easy_instant_messages"
//            })
//            notification.onclick = function() {
//              window.focus();
//              notification.close();
//              $.get("<%#= show_easy_im_window_easy_instant_messages_path(:ids => message_ids) %>");
//            }
          <!--<%# end %>-->
//          notification.onshow = function() { setTimeout(function() { notification.close() }, 30000)};
//        } else {
//          easyInstantMessageInitNotificationForChrome();
//        }
//      }
//    }
//
//    var mark = message_trigger.find("span.sign.count");
//    if (!mark[0]) {
//      mark = $("<span/>").attr({"class":"sign count"});
//      message_trigger.append(mark);
//    }
//    mark.text("<%#= @easy_instant_messages.count %>");
  <!--<%# else %>-->
//    message_trigger.removeClass('change-color-event');
//    message_trigger.find('span.sign').remove();
//    $(".easy-instant-message-list-unread-mark").remove();
  <!--<%# end %>-->

//});
window.location.reload();

plugins/easy_instant_messages/app/views/easy_instant_messages/new.html.erb
<% if false %>
<div id="easy_inline_im_container" data-user-id="<%= @user.id %>">
  <%= render(:partial => 'easy_instant_messages/inline_message_form_with_history', :formats => [:html]) %>
</div>
<script type="text/javascript">
  EASY.schedule.late(function () {
    <%=raw render(:partial => 'hyper_interval', :formats => [:js]) %>
    var chat = $("#easy_inline_im_container");
    chat.slideDown({done: function(e) {$('#easy_im_inline_message_history').scrollTop($('#easy_im_inline_message_history')[0].scrollHeight);$("#easy_instant_message_inline_chat_inputs textarea").focus()}});
  });
</script>
<% end %>

plugins/easy_instant_messages/app/views/easy_instant_messages/new.js.erb
<% if params[:hide_modal] %>
hideModal();
<% end %>
var x = document.getElementById("easy_inline_im_container");
if (x)
    x.remove();

var chat = $("<div/>").attr({id:'easy_inline_im_container', "data-user-id": "<%= @user.id %>"});
var chatContainer = $("#easy_instant_messages_list_window").hide();
chat.html("<%=j render(:partial => 'easy_instant_messages/inline_message_form_with_history') %>");
if (chatContainer[0]) {
  $("#easy_instant_messages_container.unread *[data-sender-id='<%= @user.id %>']").remove();
  chatContainer.before(chat);
} else {
  $("#easy_servicebar_component_body").html(chat);
  $("#easy_servicebar_component").easySlidingPanel({trigger: '#easy_instant_messages_list_trigger'});
  $('#easy_servicebar_close_toggler').click(function() { EasyInstantMessenger.closeChat() });
}

document.getElementById("easy_instant_message_content").focus();
EasyInstantMessenger.openChat({userId: <%= @user.id %>, senderAvatar: '<%=j avatar(@user, {style: :small, no_link: true})  %>'});
EasyInstantMessenger.chatWindow['window'] = chatContainer[0];
EasyInstantMessenger.scrollToBottomOfChatWindow();
EasyInstantMessenger.newMessagesCount = (EasyInstantMessenger.newMessagesCount - <%= @count %>);
EasyInstantMessenger.toggleNewMessageReceived();

plugins/easy_instant_messages/app/views/easy_instant_messages/toggle_sound.js.erb
<% if EasyInstantMessage.is_muted? %>
document.getElementById(EasyInstantMessenger.settings("audioTagId")).remove();
<% else %>
$("body").append("<%=j render 'audio_tag' %>");
<% end %>
$(".easy-im-sound-toggle").toggleClass('icon-mute icon-unmute').attr({title: "<%=j (EasyInstantMessage.is_muted? ? l(:title_easy_im_unmute_sound) : l(:title_easy_im_mute_sound)) %>"});